name: curve_demo
description: Demonstration of animation curves.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.3.0

environment:
  sdk: '>=3.0.0-204.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_scope:
    path: ../flutter_scope

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
