name: flutter_curves
description: Demonstration of animation curves.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.3.2

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  auto_scroll_band:
    path: ../auto_scroll_band
  flutter:
    sdk: flutter
  flutter_scope:
    path: ../flutter_scope

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
